plugin: community.digitalocean.digitalocean
attributes:
  - id
  - name
  - memory
  - size_slug
  - networks
  - tags
  - region

api_token: "{{ lookup('hashi_vault', 'secret=actions/digitalocean:token')}}"

groups:
  digitalocean: true
keyed_groups:
  - key: do_region.slug
    prefix: region
  - key: do_tags | lower
    prefix: tag

compose:
  ansible_ssh_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address')  | first
